---
# tasks file for nodejs

- block:
    - name: Add NodeSource apt key
      apt_key:
        url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
        state: 'present'

    - name: Add NodeSource repos
      apt_repository:
        repo: '{{ item }}'
        state: present
      with_items: '{{ nodejs_repos }}'

    - name: Install Node.js
      apt:
        name: 'nodejs'
        state: 'installed'
        update_cache: yes
  when: nodejs_minor_version == ''
  tags:
    - nodejs

- block:
    - name: Check if nodejs package is installed
      shell: >
        dpkg-query -W -f='${Version}' nodejs
      register: nodejs_check_deb
      failed_when: nodejs_check_deb.rc > 1
      changed_when: nodejs_check_deb.rc == 1 or nodejs_check_deb.stdout != '{{ nodejs_version }}-1nodesource1~{{ ansible_distribution_release }}1'

    - name: Install nodejs package
      apt:
        deb: 'https://deb.nodesource.com/node_{{ nodejs_major_version }}.x/pool/main/n/nodejs/nodejs_{{ nodejs_version }}-1nodesource1~{{ ansible_distribution_release }}1_amd64.deb'
      when: nodejs_check_deb.changed
  when: nodejs_minor_version != ''
  tags:
    - nodejs
